// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: apps.sql

package db

import (
	"context"
)

const getApps = `-- name: GetApps :many
SELECT id, name, description, settings, created_at, updated_at FROM apps WHERE 1 = 1
`

func (q *Queries) GetApps(ctx context.Context) ([]*Apps, error) {
	rows, err := q.db.Query(ctx, getApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Apps
	for rows.Next() {
		var i Apps
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
