// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbrepo

import (
	"context"
)

type Querier interface {
	CreateNewProjects(ctx context.Context, arg []*CreateNewProjectsParams) (int64, error)
	GetProjects(ctx context.Context) ([]*Projects, error)
}

var _ Querier = (*Queries)(nil)
