version: "3"
tasks:
  install:
    cmds:
      - go mod tidy
      - bun install
  build:style:
    cmds:
      - bun run build:esbuild
      - bun run build:tailwind
  build:templ:
    cmds:
      - templ generate
  dev:
    cmds:
      - air
